import assert from 'node:assert/strict';
import { createPlayerDamageRoute } from '../src/player-damage-route.js';
let installed=null;
const route=createPlayerDamageRoute({apply(next){installed=next;}});
let externalCalls=0;
route.setExternalInterceptor(hit=>{externalCalls++;return{...hit,damage:hit.damage-2,outcome:'external'};});
route.setDefenseResolver(hit=>({...hit,damage:0,outcome:'blocked'}));
let result=installed({damage:10,dir:{x:0,z:-1}});
assert.equal(result.damage,0);
assert.equal(result.outcome,'blocked');
assert.equal(externalCalls,0);
route.setDefenseResolver(hit=>hit);
result=installed({damage:10});
assert.equal(result.damage,8);
assert.equal(externalCalls,1);
route.setDefenseResolver(null);
result=installed({damage:5});
assert.equal(result.damage,3);
console.log('player damage route tests passed');
